global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: kairos
    metrics_path: /metrics
    static_configs:
      - targets:
          # Run kairos-alloy with: --metrics-addr 0.0.0.0:9898
          - host.docker.internal:9898
